spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  webflux:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api:
    key: sk_test_51QNlBqBhwWVqOPIE25PWrLH07t3ohVKlDaNkw3JAKypujpjCzDmDgmHA6Xs9ChutB0NSdWn2PeUYYT9RwEC8dLfM00Pgy4G31i