INSERT INTO "user" (name, age, nationality, position) VALUES
    ('Lionel Messi', 36, 'Argentina', 'Forward'),
    ('Cristiano Ronaldo', 39, 'Portugal', 'Forward'),
    ('Neymar Jr.', 32, 'Brazil', 'Forward'),
    ('Kylian Mbappé', 25, 'France', 'Forward'),
    ('Luka Modrić', 38, 'Croatia', 'Midfielder'),
    ('Kevin De Bruyne', 33, 'Belgium', 'Midfielder'),
    ('Virgil van Dijk', 32, 'Netherlands', 'Defender'),
    ('Alisson Becker', 31, 'Brazil', 'Goalkeeper'),
    ('Harry Kane', 30, 'England', 'Forward'),
    ('Mohamed Salah', 32, 'Egypt', 'Forward'),
    ('Sadio Mané', 32, 'Senegal', 'Forward'),
    ('Raheem Sterling', 29, 'England', 'Forward'),
    ('Erling Haaland', 23, 'Norway', 'Forward'),
    ('Robert Lewandowski', 35, 'Poland', 'Forward'),
    ('Thibaut Courtois', 31, 'Belgium', 'Goalkeeper'),
    ('Manuel Neuer', 38, 'Germany', 'Goalkeeper'),
    ('Sergio Ramos', 38, 'Spain', 'Defender'),
    ('Gerard Piqué', 37, 'Spain', 'Defender'),
    ('Paul Pogba', 31, 'France', 'Midfielder'),
    ('Golo Kanté', 33, 'France', 'Midfielder'),
    ('Jadon Sancho', 24, 'England', 'Forward'),
    ('Phil Foden', 24, 'England', 'Midfielder'),
    ('Trent Alexander-Arnold', 25, 'England', 'Defender'),
    ('Andrew Robertson', 30, 'Scotland', 'Defender'),
    ('Jan Oblak', 31, 'Slovenia', 'Goalkeeper'),
    ('Marcus Rashford', 26, 'England', 'Forward'),
    ('Romelu Lukaku', 31, 'Belgium', 'Forward'),
    ('Toni Kroos', 34, 'Germany', 'Midfielder'),
    ('Joshua Kimmich', 29, 'Germany', 'Midfielder'),
    ('João Cancelo', 30, 'Portugal', 'Defender'),
    ('Achraf Hakimi', 25, 'Morocco', 'Defender'),
    ('Rodri', 28, 'Spain', 'Midfielder'),
    ('Casemiro', 32, 'Brazil', 'Midfielder'),
    ('Eduardo Camavinga', 21, 'France', 'Midfielder'),
    ('Pedri', 21, 'Spain', 'Midfielder'),
    ('Gavi', 20, 'Spain', 'Midfielder'),
    ('Jude Bellingham', 21, 'England', 'Midfielder'),
    ('Vinícius Jr.', 24, 'Brazil', 'Forward'),
    ('Federico Valverde', 26, 'Uruguay', 'Midfielder'),
    ('Riyad Mahrez', 33, 'Algeria', 'Forward'),
    ('Hugo Lloris', 37, 'France', 'Goalkeeper'),
    ('Leonardo Bonucci', 36, 'Italy', 'Defender'),
    ('Giorgio Chiellini', 39, 'Italy', 'Defender'),
    ('Kalidou Koulibaly', 33, 'Senegal', 'Defender'),
    ('Édouard Mendy', 32, 'Senegal', 'Goalkeeper'),
    ('Antoine Griezmann', 33, 'France', 'Forward'),
    ('Olivier Giroud', 38, 'France', 'Forward'),
    ('Zlatan Ibrahimović', 42, 'Sweden', 'Forward'),
    ('Marco Verratti', 32, 'Italy', 'Midfielder'),
    ('Isco', 32, 'Spain', 'Midfielder'),
    ('David de Gea', 34, 'Spain', 'Goalkeeper'),
    ('Gerard Moreno', 32, 'Spain', 'Forward'),
    ('Ángel Di María', 36, 'Argentina', 'Forward'),
    ('Emiliano Martínez', 31, 'Argentina', 'Goalkeeper'),
    ('Lautaro Martínez', 26, 'Argentina', 'Forward'),
    ('Paulo Dybala', 30, 'Argentina', 'Forward'),
    ('Alexis Mac Allister', 25, 'Argentina', 'Midfielder'),
    ('Lisandro Martínez', 26, 'Argentina', 'Defender'),
    ('Christian Eriksen', 32, 'Denmark', 'Midfielder'),
    ('Pierre-Emile Højbjerg', 29, 'Denmark', 'Midfielder'),
    ('Youssef En-Nesyri', 27, 'Morocco', 'Forward'),
    ('Hakim Ziyech', 31, 'Morocco', 'Midfielder'),
    ('Sofyan Amrabat', 28, 'Morocco', 'Midfielder'),
    ('Keylor Navas', 37, 'Costa Rica', 'Goalkeeper'),
    ('Alphonso Davies', 23, 'Canada', 'Defender'),
    ('Richarlison', 27, 'Brazil', 'Forward'),
    ('Gabriel Jesus', 27, 'Brazil', 'Forward'),
    ('Eder Militão', 26, 'Brazil', 'Defender'),
    ('Thiago Silva', 39, 'Brazil', 'Defender'),
    ('Ruben Dias', 27, 'Portugal', 'Defender'),
    ('João Félix', 25, 'Portugal', 'Forward'),
    ('Diogo Jota', 27, 'Portugal', 'Forward'),
    ('Bruno Fernandes', 30, 'Portugal', 'Midfielder'),
    ('Matheus Nunes', 26, 'Portugal', 'Midfielder'),
    ('Dani Olmo', 26, 'Spain', 'Midfielder'),
    ('Unai Simón', 27, 'Spain', 'Goalkeeper'),
    ('Dusan Vlahovic', 24, 'Serbia', 'Forward'),
    ('Sergej Milinković-Savić', 29, 'Serbia', 'Midfielder'),
    ('Christian Pulisic', 25, 'USA', 'Forward'),
    ('Weston McKennie', 26, 'USA', 'Midfielder'),
    ('Tyler Adams', 25, 'USA', 'Midfielder'),
    ('Giovanni Reyna', 22, 'USA', 'Forward'),
    ('Jordan Pickford', 30, 'England', 'Goalkeeper'),
    ('Declan Rice', 25, 'England', 'Midfielder'),
    ('Mason Mount', 25, 'England', 'Midfielder'),
    ('Jack Grealish', 29, 'England', 'Midfielder'),
    ('Bukayo Saka', 23, 'England', 'Midfielder'),
    ('Reece James', 25, 'England', 'Defender'),
    ('Kyle Walker', 34, 'England', 'Defender'),
    ('Ben Chilwell', 27, 'England', 'Defender'),
    ('Marc-André ter Stegen', 32, 'Germany', 'Goalkeeper'),
    ('Jamal Musiala', 21, 'Germany', 'Midfielder'),
    ('Serge Gnabry', 29, 'Germany', 'Forward'),
    ('Thomas Müller', 35, 'Germany', 'Forward');